Diagonal shooting
UQcsse3200/2024-studio-1 pull request #461
Opened 2024-10-13 02:21 UTC by Jordamnmn

# Description
Added the ability to shoot diagonally and changed how shotgun projectiles are spawned to compensate. Also fixed a bug where the player wasn't able to shoot while touching a wall and made the player's IFrames scale with the difficulty of the game.

Fixes / Closes:
- #429
- #403 
- #290 

## Type of change

- [ ] Bug fix
- [ ] New feature

# How Has This Been Tested?

Due to shooting requiring both player input and a timer, this feature is not feasible to write tests for, however manual test has been performed to ensure that the feature works as expected 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2024-10-13 10:12 UTC, IanP96 commented
I'm still noticing something that might be a bug. Choose easy, default player, go to the wall and shoot parallel to the wall. The bullets appear very briefly then disappear, is this intentional?

2024-10-13 10:17 UTC, IanP96 reviewed
Wall shooting still doesn't appear to work, unless it's meant to be how it is. Might be an issue

2024-10-13 12:07 UTC, Jordamnmn commented
> Wall shooting still doesn't appear to work, unless it's meant to be how it is. Might be an issue

The issue was that while standing next to a wall you couldn't shoot in ANY direction, now you can shoot away from the wall. You still can't shoot parallel to the wall though, which would require changing either how projectiles or the player's collision interacts with the wall

2024-10-13 17:13 UTC, manya-k requested changes
Functionality tested, working as expected.
all files reviewed.
Please make the necessary changes as it is the last sprint

2024-10-13 17:13 UTC, manya-k commented on source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
> +    private Vector2 directionShooting = new Vector2(0, 0);
there are some IntelliJ warnings, pls fix them

2024-10-13 17:13 UTC, manya-k commented on source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
>       * @return (not sure why this needs to return)
fix javadox warnings otherwise it may fail javadoc tests in main

2024-10-13 17:13 UTC, manya-k commented on source/core/src/main/com/csse3200/game/components/weapon/FiringController.java
> +                        direction, (this.getEntity().getPosition().mulAdd(direction, 0.5F)))) {
magic number, make them constants

2024-10-14 00:11 UTC, IanP96 approved these changes
Looks good. Wall shooting and diagonal shooting work as expected. The player is invincible for longer on easy, can be seen by repeatedly trying to take damage.
The invincibility flash animation doesn't appear to scale with the iframe time, there is only one flash I can see, that may be intended however.

2024-10-14 00:25 UTC, Jordamnmn commented
> Looks good. Wall shooting and diagonal shooting work as expected. The player is invincible for longer on easy, can be seen by repeatedly trying to take damage. The invincibility flash animation doesn't appear to scale with the iframe time, there is only one flash I can see, that may be intended however.

good point, I'll make the player always flash a constant number of times before becoming vulnerable so they can tell how long the IFrames are

2024-10-14 01:36 UTC, manya-k approved these changes
everything working as expected. LGTM

2024-10-14 01:36 UTC, merged