Fix speed when move in diagonal direction and fix the sound when player take damage
UQcsse3200/2024-studio-1 pull request #463
Opened 2024-10-13 07:43 UTC by VuKhanhVyHo

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes / Closes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-13 11:04 UTC, Jordamnmn approved these changes
Looks good but it's inevitably going to cause conflicts as other member merge their code into main

2024-10-13 14:04 UTC, mblauberg approved these changes
The code looks solid overall. I noticed that this PR also includes a lot of refactors and local variable name changes in unrelated files. So it may be a good idea to update the description to mention this to give full context to future reviewers. Nice work though!

2024-10-13 17:27 UTC, manya-k requested changes
Functionality tested. 
none of the player animations are working . please fix them before the merge.

this branch has merged ui-refactor into it which had to be reverted from main so this branch cannot go in before ui-refactor.

2024-10-13 17:27 UTC, manya-k commented on source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
> +    }
none of the player animations are working in this branch

2024-10-14 01:19 UTC, manya-k commented
please fix the bugs and create a new pr when resolved so that other branches can be merged

2024-10-14 01:19 UTC, closed without merging

2024-10-14 01:24 UTC, manya-k commented on source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
> +    }
when u go left or right, the left walk or right walk animations dont work